apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: jira-metrics-postgres
    type: postgres
    access: proxy
    isDefault: true
    url: ${DATABASE_HOST}:${DATABASE_PORT}
    user: ${DATABASE_USER}
    database: ${DATABASE_NAME}
    version: 16
    secureJsonData:
      password: ${DATABASE_PASSWORD}
    jsonData:
      sslmode: disable
      maxOpenConns: 50
      maxIdleConns: 25
      connMaxLifetime: 14400
      maxIdleConnsAuto: true
      postgresVersion: 1500
      timescaledb: false
